### ISSUE TITLE
Is this library maintained? 

### ISSUE THREAD

**Issue by pbn4** [jonasblixt/ufsm#20]

**Comment by jonasblixt** [comment]
Yes

**Comment by pbn4** [comment]
I can not import choice test file `test_choice2_input.xmi` from this repository tests/ to StarUML. Could you check if it works for you?

**Comment by jonasblixt** [comment]
The XMI files in the test-directory only contains the logical representation of the machine and no graphical information so it's unlikely that they can be imported in any meaningful way in staruml

**Comment by jonasblixt** [comment]
There are som "mdj" files in the doc folder, those are staruml project files
